# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PORT: 3000
  MONGODB_URL: mongodb://127.0.0.1:27017/test
  JWT_SECRET: thisisasamplesecret
  JWT_ACCESS_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRATION_DAYS: 30
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [4.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./server/package-lock.json"
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}        
    - name: Install Dependecies
      run: |
        cd ./server
        npm install
    - name: Run Lint
      run: |
        cd ./server
        npm run lint    
    - name: Run Unit Tests
      run: |
        cd ./server
        npm test

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [4.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./server/package-lock.json"
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}   
    - name: NPM Install
      run: |
        cd ./server
        npm install
    - name: Generate Coverage
      run: |
        cd ./server
        npm run coverage:coveralls
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: 2e8c261948d20049df4ea28b0b28d7f0e69423686dbb37ebd9eeb64248238a62
      with:
        debug: true
        workingDirectory: ${{github.workspace}}/api
        coverageCommand: "npm run coverage:coveralls"
        coverageLocations: |
          ${{github.workspace}}/api/coverage/*.lcov:lcov
